language: ruby
rvm:
  - 2.6.1
  - 2.5.4
  - 2.4.5
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - gem update --system
  - gem install bundler:2.0.1
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:setup
script:
  - bin/rails test
  - bin/rspec
