language: ruby
rvm:
  - "2.0.0"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - rake db:setup
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
