language: ruby
rvm:
  - "2.0.0"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup
script:
  - bundle exec rake
  - bundle exec rspec
