:languages:
  :xcl:
    :instance_frequencies:
      true
    :inflections_table:
      true
    :source_tag_pattern_filtering:
      true
  :got:
    :instance_frequencies:
      true
    :source_tag_pattern_filtering:
      true
    :include_new_source_tags:
      "^V":
      "^N":
      "^A":
      "^P":
      "^Mo":
      "^D-":
        "-n"
      "^Df":
      "^C":
    :inflections_table:
      true
  :chu:
    :fst:
      :normalisation:
        cu-normalisation.ca
      :analysis:
        cu.ca
      :orthography:
        cu-orthographics.ca
    :instance_frequencies:
      true
    :inflections_table:
      true
    :source_tag_pattern_filtering:
      true
  :grc:
    :instance_frequencies:
      true
    :source_tag_pattern_filtering:
      true
    :include_new_source_tags:
      "^N-":
        "-b"
      "^N[^-]":
        "-"
      "^A........-":
        "---------p"
      "^A........[^-]":
        "-"
      "^V":
        "-"
    :inflections_table:
      true
  :lat:
    :instance_frequencies:
      true
    :inflections_table:
      true
